name: Lint Code Base

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [assigned, opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v2

      - name: Lint Codebase
        uses: github/super-linter@v2.2.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSON: false
          VALIDATE_ANSIBLE: false
